version: 2
updates:
  # Set update schedule for GitHub Actions
  # https://docs.github.com/fr/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Dependabot Containerfile does not fully support Containerfiles yet
  # https://github.com/dependabot/dependabot-core/issues/11320
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
