name: build image
on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!**/README.md'
      - '!**/README.org'
      - '!**/renovate.json'
      - '!.forgejo/**'
      - '.forgejo/workflows/build.yml'
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**/README.md'
      - '!**/README.org'
      - '!**/renovate.json'
      - '!.forgejo/**'
      - '.forgejo/workflows/build.yml'
  workflow_dispatch:
  schedule:
    # Build every day at 5:00 AM
    # fedora-bootc image is built around 4:30 AM
    - cron: '0 5 * * *'

env:
  REGISTRY: forgejo.clmnt.xyz
  REPOSITORY: ${{ forgejo.repository }}
  IMAGE_TAGS: ${{ forgejo.sha }} latest

  LOGLEVEL: warn # warn is the default value

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.ref || forgejo.run_id }}
  cancel-in-progress: ${{ forgejo.event_name == 'pull_request' }}

jobs:
  build-push:
    name: build image
    runs-on: podman
    container:
      image: ghcr.io/clement-dufour/actions-runner
      options:
        --volume containers_storage:/home/podman/.local/share/containers/storage:z
    strategy:
      fail-fast: false

    # key not yet supported on forgejo, keeping it for reference
    # permissions:
    #   contents: read
    #   packages: write # needed for pushing package to GHCR
    #   #id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - name: checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: change containers signature policy
        run: |
          mkdir -p "${HOME}/.config/containers/registries.d"

          cat << EOF > "${HOME}/.config/containers/registries.d/default-docker.yaml"
          default-docker:
            use-sigstore-attachments: true
          EOF

          cat << EOF > "${HOME}/.config/containers/policy.json"
          {
            "default": [
              {
                "type": "reject"
              }
            ],
            "transports": {
              "docker": {
                "quay.io/fedora-ostree-desktops": [
                  {
                    "type": "sigstoreSigned",
                    "keyData": "$(base64 -w 0 "${FORGEJO_WORKSPACE}/quay.io-fedora-ostree-desktops.pub")",
                    "signedIdentity": {
                        "type": "matchRepository"
                    }
                  }
                ]
              }
            }
          }
          EOF

      - name: build
        id: build
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          image_with_tag=""
          for tag in ${IMAGE_TAGS}; do
            if [ -z "${image_with_tag}" ]; then
              image_with_tag="${REGISTRY}/${REPOSITORY}:${tag}"
              buildah --log-level "${LOGLEVEL}" bud --file "${FORGEJO_WORKSPACE}/Containerfile" --format oci --tag "${image_with_tag}" "${FORGEJO_WORKSPACE}"
            else
              buildah --log-level "${LOGLEVEL}" tag "${image_with_tag}" "${REGISTRY}/${REPOSITORY}:${tag}"
            fi
          done

          {
            printf 'image-with-tag=%s\n' "${image_with_tag}"
          } >> "${FORGEJO_OUTPUT}"

      - name: perform static analysis checks
        env:
          IMAGE_WITH_TAG: ${{ steps.build.outputs.image-with-tag }}
        run: |
          podman --log-level "${LOGLEVEL}" run --rm ${IMAGE_WITH_TAG} bootc container lint --fatal-warnings

      - name: login to container registry
        id: login
        if: (forgejo.event_name == 'push' || forgejo.event_name == 'workflow_dispatch') && forgejo.ref == 'refs/heads/main'
        env:
          REGISTRY_USER: ${{ forgejo.actor }}
          REGISTRY_PASSWORD: ${{ secrets.TOKEN_PACKAGES_RW }}
        run: |
          podman --log-level "${LOGLEVEL}" login --username "${REGISTRY_USER}" --password "${REGISTRY_PASSWORD}" "${REGISTRY}"

      - name: push to registry
        id: push
        if: (forgejo.event_name == 'push' || forgejo.event_name == 'workflow_dispatch') && forgejo.ref == 'refs/heads/main'
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          for tag in ${IMAGE_TAGS}; do
            podman --log-level "${LOGLEVEL}" push --sign-by-sigstore-private-key <(printf '%s\n' "${COSIGN_PRIVATE_KEY}") "${REGISTRY}/${REPOSITORY}:${tag}"
          done

      - name: logout from container registry
        if: always() && (steps.login.outcome == 'success' || steps.login.outcome == 'failure' )
        run: |
          podman --log-level "${LOGLEVEL}" logout "${REGISTRY}"

  cleanup:
    name: cleanup
    if: always()
    needs: [build-push]
    runs-on: podman
    container:
      image: ghcr.io/clement-dufour/actions-runner
      options:
        --volume containers_storage:/home/podman/.local/share/containers/storage:z

    steps:
      - name: cleanup local image storage
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          for tag in ${IMAGE_TAGS}; do
            podman --log-level "${LOGLEVEL}" image rm "${REGISTRY}/${REPOSITORY}:${tag}"
          done
          podman --log-level "${LOGLEVEL}" system prune --force
