name: ci-build
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'renovate/**'
    paths:
      - '**'
      - '!README.*'
      - '!renovate.json'
      - '!.forgejo/**'
      - '.forgejo/workflows/ci-build.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - '**'
      - '!README.*'
      - '!renovate.json'
      - '!.forgejo/**'
      - '.forgejo/workflows/ci-build.yml'

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.ref || forgejo.run_id }}
  cancel-in-progress: ${{ forgejo.event_name == 'pull_request' }}

jobs:
  build:
    name: build
    runs-on: podman-builder
    uses: clmnt/container-images/.forgejo/workflows/reusable-build.yml@742e14b53085fc95291b2c79eb7324fd06276485 # v1.0.0

    with:
      image-names: |
        forgejo.clmnt.xyz/${{ forgejo.repository }}:${{ forgejo.sha }}
        forgejo.clmnt.xyz/${{ forgejo.repository }}:latest
      containers-policy: ./containers-policy.json
    secrets:
      registry-user: ${{ forgejo.actor }}
      registry-password: ${{ secrets.TOKEN_PACKAGES_RW }}
      sigstore-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
