name: ci-build
on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!README.*'
      - '!renovate.json'
      - '!.forgejo/**'
      - '.forgejo/workflows/ci-build.yml'

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.ref || forgejo.run_id }}
  cancel-in-progress: ${{ forgejo.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: podman-builder
    uses: clmnt/container-images/.forgejo/workflows/reusable-build.yml@93c4fb5f6c9b7861448146a0833217ce41de9375 # v1.1

    with:
      image-names: |
        forgejo.clmnt.xyz/${{ forgejo.repository }}:${{ forgejo.sha }}
        forgejo.clmnt.xyz/${{ forgejo.repository }}:latest
      containers-policy: ./containers-policy.json
    secrets:
      registry-user: ${{ forgejo.actor }}
      registry-password: ${{ secrets.TOKEN_PACKAGES_RW }}
      sigstore-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
