name: renovate-config-validator
on:
  workflow_dispatch:
  push:
    paths:
      - 'renovate.json'
      - '.forgejo/workflows/renovate-config-validator.yml'

jobs:
  renovate-config-validator:
    runs-on: podman-unprivileged
    container:
      image: ghcr.io/renovatebot/renovate:44@sha256:c1cb952b2e14a112d0d0c61987a10f60a2626fe9b9c1504436be46a17bd123bc
    strategy:
      fail-fast: true
      matrix:
        config-file:
          - 'renovate.json'

    steps:
      - name: checkout repository
        uses: https://code.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: validate renovate configuration
        env:
          CONFIG_FILE: ${{ matrix.config-file }}
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          renovate-config-validator --strict --no-global "${CONFIG_FILE}"
