name: renovate-config-validator
on:
  workflow_dispatch:
  push:
    paths:
      - 'renovate.json'
      - '.forgejo/workflows/renovate-config-validator.yml'

jobs:
  renovate-config-validator:
    runs-on: podman-unprivileged
    container:
      image: ghcr.io/renovatebot/renovate:43@sha256:b4c05f43e95841808410b1b2c106bbf4560218c6dbe847abcde22a9fa9ece7e1
    strategy:
      fail-fast: true
      matrix:
        config-file:
          - 'renovate.json'

    steps:
      - name: checkout repository
        uses: https://code.forgejo.org/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: validate renovate configuration
        env:
          CONFIG_FILE: ${{ matrix.config-file }}
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          renovate-config-validator --strict --no-global "${CONFIG_FILE}"
