name: Build image
on:
  merge_group:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!**/README.org'
      - '!.github/**'
      - '.github/workflows/build.yml'
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**/README.org'
      - '!.github/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  NAMESPACE: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAGS: latest ${{ github.sha }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-push:
    name: Build image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    permissions:
      contents: read
      packages: write # needed for pushing package to GHCR
      #id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Cosign
        uses: sigstore/cosign-installer@7e8b541eb2e61bf99390e1afd4be13a184e9ebc5 # v3.10.1

      - name: Change containers signature policy file
        run: |
          /usr/bin/sudo /usr/bin/cp --recursive build_files/. /

      - name: Build
        id: build
        shell: bash
        run: |
          set -oue pipefail
          set -x

          image_with_tag=""
          for tag in ${IMAGE_TAGS}; do
            if [ -z "${image_with_tag}" ]; then
              image_with_tag="${IMAGE_NAME}:${tag}"
              /usr/bin/buildah bud --file "${GITHUB_WORKSPACE}/Containerfile" --format oci --tag "${image_with_tag}" "${GITHUB_WORKSPACE}"
            else
              /usr/bin/buildah tag "${image_with_tag}" "${IMAGE_NAME}:${tag}"
            fi
          done

          {
            printf 'image_with_tag=%s\n' "${image_with_tag}"
          } >> ${GITHUB_OUTPUT}

      - name: Perform static analysis checks
        env:
          IMAGE_WITH_TAG: ${{ steps.build.outputs.image-with-tag }}
        run: |
          /usr/bin/podman run --rm localhost/${IMAGE_WITH_TAG} bootc container lint --fatal-warnings

      - name: Push to registry
        id: push
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          set -oue pipefail
          set -x

          for tag in "${IMAGE_TAGS}"; do
            /usr/bin/podman push --quiet --digestfile digest.txt --creds="${REGISTRY_USER}:{REGISTRY_PASSWORD}" "${IMAGE_NAME}:${tag}" "${REGISTRY}/${NAMESPACE}/${IMAGE_NAME}:${tag}"
          done

          {
            printf 'digest=%s\n' "$(head -n 1 digest.txt)"
          } >> ${GITHUB_OUTPUT}

      - name: Login to GitHub Container Registry
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          /usr/bin/podman login --username "${REGISTRY_USER}" --password "{REGISTRY_PASSWORD}" "${REGISTRY}"

      - name: Sign image with a key
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          /usr/bin/cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${REGISTRY}/${NAMESPACE}/${IMAGE_NAME}@${DIGEST}"
